# 1. START ->
# 2. GENERATE A RANDOM WORD -> 
# 3. GENERATE AS MANY BLANKS AS LETTERS IN WORD (HOW MANY LETTERS IN THE WORD) -> 


# 4. ####### ASK THE USER TO GUESS A LETTER -> ##########
# 5. IS THE GUESSED LETTER IN THE WORD?
# YES : REPLACE THE BLANK WITH LETTER - > ARE ALL THE BLANKS FILLED ? -> NO: ASK THE USER TO GUESS A LETTER (TOP LOOP) / YES: END THE GAMEE
# NO : LOSE A LIFE -> HAVE THEY RUN OUT OF LINES? NO: ASK THE USER TO GUESS A LETTER (TOP LOOP) / YES: END THE GAMEE


def hangman():
    